### ISSUE TITLE
how to use the okta in oc project

### ISSUE THREAD

**Issue by jinliyuelong** [okta/okta-sdk-appauth-ios#71] opened 2018-09-05 08:37 UTC
how to use the okta in oc project

**Comment by nbarbettini** [comment] 2018-10-19 20:30
Closing as a duplicate of: https://github.com/okta/okta-sdk-appauth-ios/issues/43

We will close #43 when we've added this documentation.

**Closed by nbarbettini** 2018-10-19 20:30 UTC
