### ISSUE TITLE
Login is hanging

### ISSUE THREAD

**Issue by gabehoffman** [okta/okta-sdk-appauth-ios#110] opened 2019-01-09 21:26 UTC
I just updated to 1.0.1 from 0.3.0, made the very minor code changes to accommodate the Hydra promise flow. Made the changes needed to the `Okta.plist`. Made the switch to point my pods to this repo, instead of the out of date Cocoapods version. And now "Sign In" is just hanging. I can put in the user name and password and then I get a permanent hang on this screen. At this point in the code, I don't have control of the screen, so I don't think the error is in my code. And I've confirmed everything is working as expected when I roll back the code, so I don't think there is something wrong with the service.

My only hunch is that it's something wrong with the callback into the app.

I'll keep digging.

## Screen Shot
![simulator screen shot - iphone xs max - 2019-01-09 at 15 37 21](https://user-images.githubusercontent.com/2106257/50929453-35300700-142b-11e9-8a68-626e492e65ab.png)

**Comment by anastasiiaiurok-okta** [comment] 2019-01-15 10:31
Hi @gabehoffman , thanks for the report.
It looks like redirect from the browser to your app does not work. Could you please check whether Info.plist file contains URL scheme that corresponds to redirect URI used for sign in. Also, app should handle redirect in AppDelegate by passing redirect URL to Okta. All the deals are specified in "Handle the redirect" of REAME. Please let us know whether this issue still reproducible.

**Comment by gabehoffman** [comment] 2019-01-31 18:25
Updated to 2.0 -  We have two apps. One is just basically a glorified version of your test app. I can't get it working in that app. It's just hanging. It's getting the callback in AppDelegate, and I have the right code there, but it's like it doesn't know what to do with it. And then in our real app. I have it working with the 2.0 code. I'm doing the same things in both apps. Using different URL schemas as well. Not sure why it won't log in with the test app.

**Comment by anastasiiaiurok-okta** [comment] 2019-02-06 15:55
Seams like redirect doest not work for the test app. Could you please show sources of test app so we could investigate it?

**Comment by gabehoffman** [comment] 2019-02-06 15:59
I can't post the source code publicly. But I'd be happy to get on a screen share and let you take a look. Or perhaps I can get you access to our repo.

**Comment by anastasiiaiurok-okta** [comment] 2019-02-06 16:00
I think access to the repo might help.

**Comment by gabehoffman** [comment] 2019-02-06 16:13
I could save you a lot of time by showing you where to look.  There's very little Okta code really.

Let's see what we can set up - gabe.hoffman@accesscfa.com

**Comment by anastasiiaiurok-okta** [comment] 2019-02-08 11:19
Issue occurs because improper import of Okta SDK into the app. Several implementation of the same class exists in runtime. That causes issues on login. 
@gabehoffman Please, let us know whether we can close this issue.

**Comment by gabehoffman** [comment] 2019-02-08 18:50
This is correct. It was pulling in different libs. Thanks for your help.

**Closed** 2019-02-09 18:35 UTC
Labels: In Progress
